name:  CI-with-Composite-Action

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

permissions:
  packages: write

jobs:
    job1:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: mina-magdy3/github-actions/.github/actions/composite-action@main
              with:
                  node_version: 20
                  cache_path: |
                    node_modules
                    ~/.npm
            - run: npm run lint
            - run: npm run test
            - run: npm run build
           
  
  
