name: custom action using docker 
on:
    workflow_dispatch:
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - uses: mina-magdy3/custom-action-using-docker/.github/actions/folder@main
            with:
                messsage: "hello world"
                 