name: CI Using Template

on:
#   push:
#     branches: [ "main" ]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  React-CI:
    uses: minamagdy3/github-actions/.github/workflows/template.yml@main
    with:
      node-version: '20'
      docker_imagename: react-app-cicd
      lint_phase: false
      unit_test: false
      docker_username: ${{ github.actor }}
      docker_registery: ghcr.io
      docker_tag: latest


    secrets:
        docker_password: ${{ secrets.GITHUB_TOKEN }}
    

