name: runtime-env
on:
    workflow_dispatch
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "GREETING=$(Hello,github actions)" >> $GITHUB_ENV
            - run : |
                echo "$GREETING"
            - run: |
                 echo "GREETING=$(Hello,your name,github actions)" >> $GITHUB_ENV
            - run : |
                 echo "$GREETING"