name: template
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      unit_test:
        required: true
        type: boolean
      lint_phase:
        required: true
        type: boolean
      docker_registery:
        required: true
        type: string
      docker_username:
        required: true
        type: string
      docker_imagename:
        required: true
        type: string
      docker_tag:
        required: true
        type: string
    secrets:
      docker_password:
        required: true
jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: install node version 20
              uses: actions/setup-node@v6.1.0
              with: 
                node-version: ${{inputs.node_version}}
            - run: npm install
            - run: npm run lint
            - run: npm run test
            - run: npm run build
            - name: docker login 
              uses: docker/login-action@v2
              with:
                registry: ${{inputs.docker_registery}}
                username:  ${{ inputs.docker_username }}
                password: ${{ secrets.docker_password }}
            - name: build 
              uses: docker/build-push-action@v6.18.0
              with: 
                push: true
                context: .
                tags: ${{inputs.docker_registery}}/${{ inputs.docker_username }}/${{inputs.docker_imagename}}:${{inputs.docker_tag}}